In [1]:
print("Hello,World!")

Hello,World!

In [7]:
import pandas as pd
import numpy as np


data = np.random.rand(8,5)
df = pd.DataFrame(
    data = data,
    index = ['row1', 'row2','row3','row4','row5','row6','row7','row8'],
    columns = ['col1', 'col2', 'col3', 'col4', 'col5']
)

df

          col1      col2      col3      col4      col5
row1  0.002583  0.194583  0.969032  0.869017  0.002487
row2  0.445375  0.513005  0.408396  0.477029  0.692059
row3  0.473320  0.830054  0.033231  0.808067  0.818172
row4  0.582302  0.480186  0.610752  0.408082  0.914878
row5  0.585815  0.880112  0.870634  0.568186  0.394906
row6  0.690846  0.001258  0.621872  0.272137  0.972462
row7  0.296926  0.756888  0.794598  0.654542  0.951243
row8  0.489950  0.077110  0.754282  0.337870  0.486216

In [8]:
df < 0

       col1   col2   col3   col4   col5
row1  False  False  False  False  False
row2  False  False  False  False  False
row3  False  False  False  False  False
row4  False  False  False  False  False
row5  False  False  False  False  False
row6  False  False  False  False  False
row7  False  False  False  False  False
row8  False  False  False  False  False

In [9]:
df > 0

      col1  col2  col3  col4  col5
row1  True  True  True  True  True
row2  True  True  True  True  True
row3  True  True  True  True  True
row4  True  True  True  True  True
row5  True  True  True  True  True
row6  True  True  True  True  True
row7  True  True  True  True  True
row8  True  True  True  True  True